# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 08:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('over_night_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Cleaner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cl_name', models.CharField(max_length=255)),
                ('cl_phone', models.CharField(max_length=10)),
                ('cl_address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CleanInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cl_date', models.DateTimeField()),
                ('cleaner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orderRoom.Cleaner')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('c_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=255)),
                ('c_phone', models.CharField(max_length=10)),
                ('c_address', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_name', models.CharField(max_length=255)),
                ('e_phone', models.CharField(max_length=10)),
                ('e_address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_date', models.DateTimeField()),
                ('o_status', models.CharField(max_length=10)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orderRoom.Customer')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orderRoom.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_money', models.IntegerField(default=0)),
                ('p_account', models.CharField(max_length=255)),
                ('p_date', models.DateTimeField()),
                ('order', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orderRoom.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('r_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rt_name', models.CharField(max_length=255)),
                ('rt_money', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_bike', models.CharField(max_length=1)),
                ('s_breakfast', models.CharField(max_length=1)),
                ('s_gym', models.CharField(max_length=1)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orderRoom.Order')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orderRoom.RoomType'),
        ),
        migrations.AddField(
            model_name='cleaninfo',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orderRoom.Room'),
        ),
        migrations.AddField(
            model_name='bookingroom',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orderRoom.Order'),
        ),
        migrations.AddField(
            model_name='bookingroom',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orderRoom.Room'),
        ),
    ]
