# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-14 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderRoom', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clean_info',
            new_name='CleanInfo',
        ),
        migrations.AddField(
            model_name='room',
            name='r_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roomtype',
            name='rt_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
