# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-15 04:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orderRoom', '0002_auto_20160514_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomsOfOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimate_checkin_date', models.DateTimeField()),
                ('estimate_checkout_date', models.DateTimeField()),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orderRoom.Order')),
            ],
        ),
        migrations.RemoveField(
            model_name='room',
            name='cleaner',
        ),
        migrations.RemoveField(
            model_name='room',
            name='order',
        ),
        migrations.AlterField(
            model_name='cleaninfo',
            name='cleaner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orderRoom.Cleaner'),
        ),
        migrations.AlterField(
            model_name='cleaninfo',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orderRoom.Room'),
        ),
        migrations.AddField(
            model_name='roomsoforder',
            name='room',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='orderRoom.Room'),
        ),
    ]
