# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-15 10:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orderRoom', '0003_auto_20160515_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='id',
        ),
        migrations.RemoveField(
            model_name='room',
            name='id',
        ),
        migrations.RemoveField(
            model_name='roomtype',
            name='id',
        ),
        migrations.AddField(
            model_name='customer',
            name='c_id',
            field=models.CharField(default='', max_length=10, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='r_name',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='roomsoforder',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orderRoom.Order'),
        ),
        migrations.AlterField(
            model_name='roomsoforder',
            name='room',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orderRoom.Room'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='rt_name',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
