# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-15 11:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orderRoom', '0004_auto_20160515_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomsoforder',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orderRoom.Room'),
        ),
    ]
