# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-16 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderRoom', '0006_auto_20160516_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='c_address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
