# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-21 10:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orderRoom', '0007_auto_20160516_1328'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RoomsOfOrder',
            new_name='BookingRoom',
        ),
        migrations.AddField(
            model_name='order',
            name='o_status',
            field=models.CharField(default='Booking', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orderRoom.Employee'),
        ),
    ]
